import turtle
turtle.speed(0)
square=turtle.Screen()
square.bgcolor("tan")
square.title("Square")
mypen=turtle.Turtle()
mypen.forward(100)
mypen.right(90)
mypen.forward(100)
mypen.right(90)
mypen.forward(100)
mypen.right(90)
mypen.forward(100)
mypen.right(90)